### ISSUE TITLE
Enemy Move name isn't the same as the damage name

### ISSUE THREAD

**Issue by jack25440** [p0isonedpanda/RPGBase#2]
When i was working on the fork, i tested out attacking but when the enemy player attacked after i did it's move name didn't match the name of the move that had that damage number. I cloned the it directly to my desktop to test it fresh to see if it was just me but it still happened with the original. This might just be a feature you put in though 

Enemy attacked with Skrrt dealing 20 damage!

new PlayerMove("Yeet", MoveType.Magic, 20, 8, 0),
new PlayerMove("Skrrt", MoveType.Physical, 15, 0, 6)

**Comment by pondodev** [comment]
Attacking is working as intended, what you're seeing is a product of the damage modification system. The way this works is when you attack, it calculates damage dealt based off the attack and defence for the respective attack type. Skrrt is a special (or as you changed it it, magic) move which means an attack mod of 10 is applied to the move. Then the defence modifier is taken away from the total which is 5 in this case, making the total damage 20.
